// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fec_type.proto
// Protobuf C++ Version: 5.26.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_fec_5ftype_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_fec_5ftype_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 5026001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_fec_5ftype_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_fec_5ftype_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_fec_5ftype_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum FecType : int {
  FEC_NONE = 0,
  FEC_2_1 = 1,
  FEC_3_1 = 2,
  FEC_3_2 = 3,
  FEC_4_1 = 4,
  FEC_4_2 = 5,
  FEC_4_3 = 6,
  FEC_5_1 = 7,
  FEC_5_2 = 8,
  FEC_5_3 = 9,
  FEC_5_4 = 10,
  FEC_6_1 = 11,
  FEC_6_2 = 12,
  FEC_6_3 = 13,
  FEC_6_4 = 14,
  FEC_7_1 = 15,
  FecType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  FecType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool FecType_IsValid(int value);
extern const uint32_t FecType_internal_data_[];
constexpr FecType FecType_MIN = static_cast<FecType>(0);
constexpr FecType FecType_MAX = static_cast<FecType>(15);
constexpr int FecType_ARRAYSIZE = 15 + 1;
const ::google::protobuf::EnumDescriptor*
FecType_descriptor();
template <typename T>
const std::string& FecType_Name(T value) {
  static_assert(std::is_same<T, FecType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to FecType_Name().");
  return FecType_Name(static_cast<FecType>(value));
}
template <>
inline const std::string& FecType_Name(FecType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<FecType_descriptor,
                                                 0, 15>(
      static_cast<int>(value));
}
inline bool FecType_Parse(absl::string_view name, FecType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FecType>(
      FecType_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::FecType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::FecType>() {
  return ::FecType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_fec_5ftype_2eproto_2epb_2eh
