// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cipher_type.proto
// Protobuf C++ Version: 5.26.1

#include "cipher_type.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_cipher_5ftype_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_cipher_5ftype_2eproto = nullptr;
const ::uint32_t TableStruct_cipher_5ftype_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_cipher_5ftype_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021cipher_type.proto*1\n\nCipherType\022\010\n\004Non"
    "e\020\000\022\014\n\010ChaCha20\020\001\022\013\n\007AES_GCM\020\002b\006proto3"
};
static ::absl::once_flag descriptor_table_cipher_5ftype_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_cipher_5ftype_2eproto = {
    false,
    false,
    78,
    descriptor_table_protodef_cipher_5ftype_2eproto,
    "cipher_type.proto",
    &descriptor_table_cipher_5ftype_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_cipher_5ftype_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_cipher_5ftype_2eproto,
    file_level_service_descriptors_cipher_5ftype_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_cipher_5ftype_2eproto_getter() {
  return &descriptor_table_cipher_5ftype_2eproto;
}
const ::google::protobuf::EnumDescriptor* CipherType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_cipher_5ftype_2eproto);
  return file_level_enum_descriptors_cipher_5ftype_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CipherType_internal_data_[] = {
    196608u, 0u, };
bool CipherType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_cipher_5ftype_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
